REQUIRED_PYTHON: python3
platform_params:
  keyword_search_mode: True
  amazon_fresh_mode: True
  bigbasket_mode: True
  flipkart_mode: True

platform_urls:
  amazon_fresh:
    url_1st: pass
    url_2nd: pass
  flipkart:
    url: pass
  bigbasket:
    main_url: https://www.bigbasket.com
    all_categories_url: https://www.bigbasket.com/product/all-categories/

path_params:
  amazon_crawler_path: src/amazon_crawler/
  flipkart_crawler_path: src/flipkart_crawler/
  bigbasket_crawler_path: src/bigbasket_crawler/
  output_images_path: data/images/
  output_catalogue_csv_path: data/catalogue/
  url_files_path: data/url_files/
  user_agent_path: data/user_agent_list/
  proxylist_path: data/proxy_list/

files_names:
  keyword_file: keywords.txt
  output_catalogue_csv: catalogue.csv
  bigbasket_main_url_file: bigbasket.csv
  user_agent_file: user_agent_list.txt
  proxylist_file: proxy_list.txt
  bigbasket_scrapped_urls: bigbasket_scrapped_urls.csv